#include <blik.h>
#if BLIK_NEED_ADDON_H264

// 도구준비
#include <addon/blik_fakewin.h>
#include "blik_integration_openh264-1.6.0.h"

#include <addon/openh264-1.6.0_for_blik/codec/common/src/common_tables.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/copy_mb.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/cpu.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/crt_util_safe_x.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/deblocking_common.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/expand_pic.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/intra_pred_common.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/mc.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/memory_align.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/sad_common.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/utils.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/welsCodecTrace.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/WelsTaskThread.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/WelsThread.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/WelsThreadLib.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/common/src/WelsThreadPool.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/au_set.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/deblocking.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/decode_mb_aux.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/encoder.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/encoder_data_tables.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/encoder_ext.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/encode_mb_aux.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/get_intra_predictor.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/md.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/mv_pred.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/nal_encap.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/paraset_strategy.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/picture_handle.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/ratectl.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/ref_list_mgr_svc.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/sample.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/set_mb_syn_cabac.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/set_mb_syn_cavlc.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/slice_multi_threading.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_base_layer_md.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_encode_mb.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_encode_slice.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_enc_slice_segment.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_mode_decision.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_motion_estimate.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_set_mb_syn_cabac.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/svc_set_mb_syn_cavlc.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/wels_preprocess.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/wels_task_base.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/wels_task_encoder.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/core/src/wels_task_management.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/encoder/plus/src/welsEncoderExt.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/adaptivequantization/AdaptiveQuantization.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/backgrounddetection/BackgroundDetection.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/common/WelsFrameWork.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/common/WelsFrameWorkEx.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/common/memory.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/complexityanalysis/ComplexityAnalysis.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/denoise/denoise.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/denoise/denoise_filter.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/downsample/downsample.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/downsample/downsamplefuncs.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/imagerotate/imagerotate.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/imagerotate/imagerotatefuncs.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/scenechangedetection/SceneChangeDetection.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/scrolldetection/ScrollDetection.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/scrolldetection/ScrollDetectionFuncs.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/vaacalc/vaacalcfuncs.cpp>
#include <addon/openh264-1.6.0_for_blik/codec/processing/src/vaacalc/vaacalculation.cpp>

#endif
